name: color_chart
description: A non-material and classified color chart for Flutter development.
version: 0.0.0
repository: https://github.com/aprosail/color-chart
environment: {sdk: ">=3.4.0 <4.0.0", flutter: ">=3.22.0"}
topics:
  - flutter
  - color
  - color-chart

dependencies:
  flutter: {sdk: flutter}

dev_dependencies:
  flutter_test: {sdk: flutter}
  strict_lints: ^0.1.0
